--DROP TABLE BankBranch;
IF (NOT EXISTS (SELECT 1 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'BankBranch'))
BEGIN
	CREATE TABLE BankBranch
	(
		Id INT CONSTRAINT PK_BankBranch PRIMARY KEY IDENTITY(1,1),
		Code VARCHAR(500) CONSTRAINT UQ_BankBranch_Code UNIQUE(Code) NOT NULL,
		Address1 VARCHAR(1000) NOT NULL,
		Address2 VARCHAR(1000),
		City VARCHAR(500) NOT NULL,
		District VARCHAR(500) NOT NULL,
		[State] VARCHAR(500) NOT NULL,
		ZipCode VARCHAR(10) NOT NULL,
		BankId INT CONSTRAINT FK_BankBranch_BankId FOREIGN KEY REFERENCES Bank(Id) NOT NULL,
		CreatedDate DATETIME NOT NULL,
		UpdatedDate DATETIME NOT NULL
	);
END